#!/usr/bin/env python

## MQAP
# Copyright (C) 2013 Gokcen Eraslan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import argparse
import sys

from generateTraining import generateTrainingSet
from train import train
from predict import predict
from rank import rank
from crossvalidation import crossvalidate

# we are using argparse module to implement argument parsing
parser = argparse.ArgumentParser()

# argparse can be used to implement git-style subcommand based arguments
subparsers = parser.add_subparsers(title='Subcommands',
                                   description='This program requires a '
             'mandatory subcommand (like git). See "%s <command> -h" to '
             'read about a specific subcommand.' % sys.argv[0],
             dest='subcommand')

# generatetraining subcommand ############################
generatetraining = subparsers.add_parser('generatetraining',
                                         help='Generates training set')

generatetraining.add_argument('-t', '--target', help='Target structure in '
                              'PDB format.', required=True)

generatetraining.add_argument('-m', '--model', help='Model structure(s) in'
                              ' PDB format. Multiple files can be given.',
                              required=True, nargs='+')

generatetraining.add_argument('-o', '--output',
                              help='Name of the output file in CSV format.',
                              required=True)

generatetraining.add_argument('-d', '--distance',
                              help='Maximum distance between target and model'
                              ' atoms to determine class labels.'
                              ' Default value is 3.5 angstrom.', default=3.5,
                              type=float)

# train subcommand ############################
trainCommand = subparsers.add_parser('train', help='Trains a RandomForest '
                                     'based on given training set and '
                                     'produces a Joblib file to be used in '
                                     'prediction step.')

trainCommand.add_argument('-t', '--training',
                          help='Training set in CSV format. Class labels must'
                          ' be at the last column.', required=True)

trainCommand.add_argument('-o', '--output', help='RandomForest output file in '
                          'Joblib format.', required=True)

trainCommand.add_argument('-n', '--ntrees', help='Number of trees in the '
                          'forest. Default: 100', default=100, type=int)

# predict subcommand ############################
predictCommand = subparsers.add_parser('predict', help='Predicts the quality '
                                       'of given model file in PDB format.')

predictCommand.add_argument('-r', '--randomforest',
                            help='RandomForest input file in Joblib format.',
                            required=True)
predictCommand.add_argument('-m', '--model',
                            help='Model file(s) to be predicted in PDB format',
                            required=True, nargs='+')
predictCommand.add_argument('-o', '--output',
                            help='Model quality output file(s) in CSV format.'
                            'If not supplied, output file name will be based '
                            'on model file name.', nargs='*')

# rank subcommand ############################
rankCommand = subparsers.add_parser('rank', help='Rank given prediction '
                                       'outputs in CSV format.')

rankCommand.add_argument('-p', '--predictions',
                            help='Prediction output file(s) produced by '
                            'predict command.', nargs='+', metavar='PREDICTION')
rankCommand.add_argument('-o', '--output',
                            help='Ranking output file in CSV format.',
                            required=True)

# cv subcommand ############################
cvCommand = subparsers.add_parser('cv', help='Perform a k-fold cross '
                                    'validation using given CSV file.')

cvCommand.add_argument('-i', '--input',
                            help='In the input file, first column represents '
                                 'target file while the rest represents model '
                                 'files.', required=True)
cvCommand.add_argument('-k', '--fold', help='Fold size of k-fold CV. Default:5',
                            default=5, type=int)
cvCommand.add_argument('-o', '--output',
                            help='Cross-validation output file in CSV format.',
                            required=True)
cvCommand.add_argument('-t', '--trainingdir',
                            help='If specified, all training CSVs will be saved '
                                 'into this dir.')
cvCommand.add_argument('-r', '--randomforestdir',
                            help='If specified, all trained RFs will be saved '
                                 'into this dir in Joblib format.')
cvCommand.add_argument('-p', '--predictiondir',
                            help='If specified, all predictions will be saved '
                                 'into this dir.')
cvCommand.add_argument('-d', '--distance',
                              help='Maximum distance between target and model'
                              ' atoms to determine class labels.'
                              ' Default value is 3.5 angstrom.', default=3.5,
                              type=float)
cvCommand.add_argument('-n', '--ntrees', help='Number of trees in the '
                          'forest. Default: 100', default=100, type=int)
cvCommand.add_argument('-u', '--reuse', help='If enabled, previously saved '
                       'training/randomforest files are reused. '
                       'Default: Disabled', action='store_true')


args = parser.parse_args()


if args.subcommand.lower() == 'generatetraining':
    generateTrainingSet({args.target: args.model},
                        distance=args.distance, output=args.output)

elif args.subcommand.lower() == 'train':
    train(args.training, args.ntrees, args.output)

elif args.subcommand.lower() == 'predict':
    predict(args.randomforest, args.model, outputs=args.output,
            saveOutput=True)

elif args.subcommand.lower() == 'rank':
    rank(args.predictions, args.output)

elif args.subcommand.lower() == 'cv':
    crossvalidate(args.input, args.fold, args.output, args.distance,
                  args.ntrees, args.reuse, args.trainingdir,
                  args.randomforestdir, args.predictiondir)

else:
    sys.exit('Invalid subcommand.')
